<a href="https://colab.research.google.com/github/Venkatarameshredd/30DaysOfWebDevelopment/blob/main/Essentail_for_Data_science_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
#Take datasets in different formats (CSV, Excel, JSON, etc.) and perform data cleaning by handling empty cells, wrong formats,
#inconsistent data, and duplicates. Demonstrate missing data handling using functions like isnull(), notnull(), dropna(), fillna(), replace(), and interpolate().
# Dataset1
import pandas as pd
import numpy as np
df=pd.read_csv("https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/heart_disease.csv")
print(df)
#data cleaning
#1.Check for Missing Values
print(df.isnull())
#2.detecting  existing non missing values
print(df.notnull())

#2Drop Columns with Missing Values
print(df.dropna(axis=1))

#3.Check for Duplicate Rows
print(df.duplicated())

#4.Count Missing Values Per Column
print(df.isnull().sum())

#5.Fill Missing Values with a Constant
print(df.fillna(5))

#6replace missing values
print(df.replace(to_replace=np.nan))

#7.Fill Missing Values by Interpolation

print(df.interpolate())

     Unnamed: 0  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0             0   63    1   3       145   233    1        0      150      0
1             1   37    1   2       130   250    0        1      187      0
2             2   41    0   1       130   204    0        0      172      0
3             3   56    1   1       120   236    0        1      178      0
4             4   57    0   0       120   354    0        1      163      1
..          ...  ...  ...  ..       ...   ...  ...      ...      ...    ...
298         298   57    0   0       140   241    0        1      123      1
299         299   45    1   3       110   264    0        1      132      0
300         300   68    1   0       144   193    1        1      141      0
301         301   57    1   0       130   131    0        1      115      1
302         302   57    0   1       130   236    0        0      174      0

     oldpeak  slope  ca  thal  target
0        2.3      0   0     1       1
1        3.5      0   0     2       1
2        1.4      2   0     2       1
3        0.8      2   0     2       1
4        0.6      2   0     2       1
..       ...    ...  ..   ...     ...
298      0.2      1   0     3       0
299      1.2      1   0     3       0
300      3.4      1   2     3       0
301      1.2      1   1     3       0
302      0.0      1   1     2       0

[303 rows x 15 columns]
     Unnamed: 0    age    sex     cp  trestbps   chol    fbs  restecg  \
0         False  False  False  False     False  False  False    False
1         False  False  False  False     False  False  False    False
2         False  False  False  False     False  False  False    False
3         False  False  False  False     False  False  False    False
4         False  False  False  False     False  False  False    False
..          ...    ...    ...    ...       ...    ...    ...      ...
298       False  False  False  False     False  False  False    False
299       False  False  False  False     False  False  False    False
300       False  False  False  False     False  False  False    False
301       False  False  False  False     False  False  False    False
302       False  False  False  False     False  False  False    False

     thalach  exang  oldpeak  slope     ca   thal  target
0      False  False    False  False  False  False   False
1      False  False    False  False  False  False   False
2      False  False    False  False  False  False   False
3      False  False    False  False  False  False   False
4      False  False    False  False  False  False   False
..       ...    ...      ...    ...    ...    ...     ...
298    False  False    False  False  False  False   False
299    False  False    False  False  False  False   False
300    False  False    False  False  False  False   False
301    False  False    False  False  False  False   False
302    False  False    False  False  False  False   False

[303 rows x 15 columns]
     Unnamed: 0   age   sex    cp  trestbps  chol   fbs  restecg  thalach  \
0          True  True  True  True      True  True  True     True     True
1          True  True  True  True      True  True  True     True     True
2          True  True  True  True      True  True  True     True     True
3          True  True  True  True      True  True  True     True     True
4          True  True  True  True      True  True  True     True     True
..          ...   ...   ...   ...       ...   ...   ...      ...      ...
298        True  True  True  True      True  True  True     True     True
299        True  True  True  True      True  True  True     True     True
300        True  True  True  True      True  True  True     True     True
301        True  True  True  True      True  True  True     True     True
302        True  True  True  True      True  True  True     True     True

     exang  oldpeak  slope    ca  thal  target
0     True     True   True  True  True    True
1     True     True   True  True  True    True
2     True     True   True  True  True    True
3     True     True   True  True  True    True
4     True     True   True  True  True    True
..     ...      ...    ...   ...   ...     ...
298   True     True   True  True  True    True
299   True     True   True  True  True    True
300   True     True   True  True  True    True
301   True     True   True  True  True    True
302   True     True   True  True  True    True

[303 rows x 15 columns]
     Unnamed: 0  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0             0   63    1   3       145   233    1        0      150      0
1             1   37    1   2       130   250    0        1      187      0
2             2   41    0   1       130   204    0        0      172      0
3             3   56    1   1       120   236    0        1      178      0
4             4   57    0   0       120   354    0        1      163      1
..          ...  ...  ...  ..       ...   ...  ...      ...      ...    ...
298         298   57    0   0       140   241    0        1      123      1
299         299   45    1   3       110   264    0        1      132      0
300         300   68    1   0       144   193    1        1      141      0
301         301   57    1   0       130   131    0        1      115      1
302         302   57    0   1       130   236    0        0      174      0

     oldpeak  slope  ca  thal  target
0        2.3      0   0     1       1
1        3.5      0   0     2       1
2        1.4      2   0     2       1
3        0.8      2   0     2       1
4        0.6      2   0     2       1
..       ...    ...  ..   ...     ...
298      0.2      1   0     3       0
299      1.2      1   0     3       0
300      3.4      1   2     3       0
301      1.2      1   1     3       0
302      0.0      1   1     2       0

[303 rows x 15 columns]
0      False
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300    False
301    False
302    False
Length: 303, dtype: bool
Unnamed: 0    0
age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
slope         0
ca            0
thal          0
target        0
dtype: int64
     Unnamed: 0  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0             0   63    1   3       145   233    1        0      150      0
1             1   37    1   2       130   250    0        1      187      0
2             2   41    0   1       130   204    0        0      172      0
3             3   56    1   1       120   236    0        1      178      0
4             4   57    0   0       120   354    0        1      163      1
..          ...  ...  ...  ..       ...   ...  ...      ...      ...    ...
298         298   57    0   0       140   241    0        1      123      1
299         299   45    1   3       110   264    0        1      132      0
300         300   68    1   0       144   193    1        1      141      0
301         301   57    1   0       130   131    0        1      115      1
302         302   57    0   1       130   236    0        0      174      0

     oldpeak  slope  ca  thal  target
0        2.3      0   0     1       1
1        3.5      0   0     2       1
2        1.4      2   0     2       1
3        0.8      2   0     2       1
4        0.6      2   0     2       1
..       ...    ...  ..   ...     ...
298      0.2      1   0     3       0
299      1.2      1   0     3       0
300      3.4      1   2     3       0
301      1.2      1   1     3       0
302      0.0      1   1     2       0

[303 rows x 15 columns]
     Unnamed: 0  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0             0   63    1   3       145   233    1        0      150      0
1             1   37    1   2       130   250    0        1      187      0
2             2   41    0   1       130   204    0        0      172      0
3             3   56    1   1       120   236    0        1      178      0
4             4   57    0   0       120   354    0        1      163      1
..          ...  ...  ...  ..       ...   ...  ...      ...      ...    ...
298         298   57    0   0       140   241    0        1      123      1
299         299   45    1   3       110   264    0        1      132      0
300         300   68    1   0       144   193    1        1      141      0
301         301   57    1   0       130   131    0        1      115      1
302         302   57    0   1       130   236    0        0      174      0

     oldpeak  slope  ca  thal  target
0        2.3      0   0     1       1
1        3.5      0   0     2       1
2        1.4      2   0     2       1
3        0.8      2   0     2       1
4        0.6      2   0     2       1
..       ...    ...  ..   ...     ...
298      0.2      1   0     3       0
299      1.2      1   0     3       0
300      3.4      1   2     3       0
301      1.2      1   1     3       0
302      0.0      1   1     2       0

[303 rows x 15 columns]
     Unnamed: 0  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0             0   63    1   3       145   233    1        0      150      0
1             1   37    1   2       130   250    0        1      187      0
2             2   41    0   1       130   204    0        0      172      0
3             3   56    1   1       120   236    0        1      178      0
4             4   57    0   0       120   354    0        1      163      1
..          ...  ...  ...  ..       ...   ...  ...      ...      ...    ...
298         298   57    0   0       140   241    0        1      123      1
299         299   45    1   3       110   264    0        1      132      0
300         300   68    1   0       144   193    1        1      141      0
301         301   57    1   0       130   131    0        1      115      1
302         302   57    0   1       130   236    0        0      174      0

     oldpeak  slope  ca  thal  target
0        2.3      0   0     1       1
1        3.5      0   0     2       1
2        1.4      2   0     2       1
3        0.8      2   0     2       1
4        0.6      2   0     2       1
..       ...    ...  ..   ...     ...
298      0.2      1   0     3       0
299      1.2      1   0     3       0
300      3.4      1   2     3       0
301      1.2      1   1     3       0
302      0.0      1   1     2       0

[303 rows x 15 columns]

/tmp/ipython-input-3993742707.py:27: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  print(df.replace(to_replace=np.nan))

In [35]:
#Dataset2
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/ameenmanna8824/DATASETS/main/fruit_data_with_colors.txt", sep='\t')
print(data)
#1.Check for Missing Values
print(data.isnull())

#2.detecting existing non missing values
print(data.notnull())

#3.Drop Columns with Missing Values
print(data.dropna(axis=1))

#4.Fill Missing Values with a Constant
print(df.fillna(5))

#5.Check for Duplicate Rows
print(data.duplicated())
print(data.isnull().sum())

#6replace missing values
print(df.replace(to_replace=np.nan))

#7.Fill Missing Values by Interpolation

print(df.interpolate())

    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    5.8     8.7         0.73
50            4      lemon           unknown   130    6.0     8.2         0.71
51            4      lemon           unknown   116    6.0     7.5         0.72
52            4      lemon           unknown   118    5.9     8.0         0.72
53            4      lemon           unknown   120    6.0     8.4         0.74
54            4      lemon           unknown   116    6.1     8.5         0.71
55            4      lemon           unknown   116    6.3     7.7         0.72
56            4      lemon           unknown   116    5.9     8.1         0.73
57            4      lemon           unknown   152    6.5     8.5         0.72
58            4      lemon           unknown   118    6.1     8.1         0.70
    fruit_label  fruit_name  fruit_subtype   mass  width  height  color_score
0         False       False          False  False  False   False        False
1         False       False          False  False  False   False        False
2         False       False          False  False  False   False        False
3         False       False          False  False  False   False        False
4         False       False          False  False  False   False        False
5         False       False          False  False  False   False        False
6         False       False          False  False  False   False        False
7         False       False          False  False  False   False        False
8         False       False          False  False  False   False        False
9         False       False          False  False  False   False        False
10        False       False          False  False  False   False        False
11        False       False          False  False  False   False        False
12        False       False          False  False  False   False        False
13        False       False          False  False  False   False        False
14        False       False          False  False  False   False        False
15        False       False          False  False  False   False        False
16        False       False          False  False  False   False        False
17        False       False          False  False  False   False        False
18        False       False          False  False  False   False        False
19        False       False          False  False  False   False        False
20        False       False          False  False  False   False        False
21        False       False          False  False  False   False        False
22        False       False          False  False  False   False        False
23        False       False          False  False  False   False        False
24        False       False          False  False  False   False        False
25        False       False          False  False  False   False        False
26        False       False          False  False  False   False        False
27        False       False          False  False  False   False        False
28        False       False          False  False  False   False        False
29        False       False          False  False  False   False        False
30        False       False          False  False  False   False        False
31        False       False          False  False  False   False        False
32        False       False          False  False  False   False        False
33        False       False          False  False  False   False        False
34        False       False          False  False  False   False        False
35        False       False          False  False  False   False        False
36        False       False          False  False  False   False        False
37        False       False          False  False  False   False        False
38        False       False          False  False  False   False        False
39        False       False          False  False  False   False        False
40        False       False          False  False  False   False        False
41        False       False          False  False  False   False        False
42        False       False          False  False  False   False        False
43        False       False          False  False  False   False        False
44        False       False          False  False  False   False        False
45        False       False          False  False  False   False        False
46        False       False          False  False  False   False        False
47        False       False          False  False  False   False        False
48        False       False          False  False  False   False        False
49        False       False          False  False  False   False        False
50        False       False          False  False  False   False        False
51        False       False          False  False  False   False        False
52        False       False          False  False  False   False        False
53        False       False          False  False  False   False        False
54        False       False          False  False  False   False        False
55        False       False          False  False  False   False        False
56        False       False          False  False  False   False        False
57        False       False          False  False  False   False        False
58        False       False          False  False  False   False        False
    fruit_label  fruit_name  fruit_subtype  mass  width  height  color_score
0          True        True           True  True   True    True         True
1          True        True           True  True   True    True         True
2          True        True           True  True   True    True         True
3          True        True           True  True   True    True         True
4          True        True           True  True   True    True         True
5          True        True           True  True   True    True         True
6          True        True           True  True   True    True         True
7          True        True           True  True   True    True         True
8          True        True           True  True   True    True         True
9          True        True           True  True   True    True         True
10         True        True           True  True   True    True         True
11         True        True           True  True   True    True         True
12         True        True           True  True   True    True         True
13         True        True           True  True   True    True         True
14         True        True           True  True   True    True         True
15         True        True           True  True   True    True         True
16         True        True           True  True   True    True         True
17         True        True           True  True   True    True         True
18         True        True           True  True   True    True         True
19         True        True           True  True   True    True         True
20         True        True           True  True   True    True         True
21         True        True           True  True   True    True         True
22         True        True           True  True   True    True         True
23         True        True           True  True   True    True         True
24         True        True           True  True   True    True         True
25         True        True           True  True   True    True         True
26         True        True           True  True   True    True         True
27         True        True           True  True   True    True         True
28         True        True           True  True   True    True         True
29         True        True           True  True   True    True         True
30         True        True           True  True   True    True         True
31         True        True           True  True   True    True         True
32         True        True           True  True   True    True         True
33         True        True           True  True   True    True         True
34         True        True           True  True   True    True         True
35         True        True           True  True   True    True         True
36         True        True           True  True   True    True         True
37         True        True           True  True   True    True         True
38         True        True           True  True   True    True         True
39         True        True           True  True   True    True         True
40         True        True           True  True   True    True         True
41         True        True           True  True   True    True         True
42         True        True           True  True   True    True         True
43         True        True           True  True   True    True         True
44         True        True           True  True   True    True         True
45         True        True           True  True   True    True         True
46         True        True           True  True   True    True         True
47         True        True           True  True   True    True         True
48         True        True           True  True   True    True         True
49         True        True           True  True   True    True         True
50         True        True           True  True   True    True         True
51         True        True           True  True   True    True         True
52         True        True           True  True   True    True         True
53         True        True           True  True   True    True         True
54         True        True           True  True   True    True         True
55         True        True           True  True   True    True         True
56         True        True           True  True   True    True         True
57         True        True           True  True   True    True         True
58         True        True           True  True   True    True         True
    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    5.8     8.7         0.73
50            4      lemon           unknown   130    6.0     8.2         0.71
51            4      lemon           unknown   116    6.0     7.5         0.72
52            4      lemon           unknown   118    5.9     8.0         0.72
53            4      lemon           unknown   120    6.0     8.4         0.74
54            4      lemon           unknown   116    6.1     8.5         0.71
55            4      lemon           unknown   116    6.3     7.7         0.72
56            4      lemon           unknown   116    5.9     8.1         0.73
57            4      lemon           unknown   152    6.5     8.5         0.72
58            4      lemon           unknown   118    6.1     8.1         0.70
     Unnamed: 0  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  \
0             0   63    1   3       145   233    1        0      150      0
1             1   37    1   2       130   250    0        1      187      0
2             2   41    0   1       130   204    0        0      172      0
3             3   56    1   1       120   236    0        1      178      0
4             4   57    0   0       120   354    0        1      163      1
..          ...  ...  ...  ..       ...   ...  ...      ...      ...    ...
298         298   57    0   0       140   241    0        1      123      1
299         299   45    1   3       110   264    0        1      132      0
300         300   68    1   0       144   193    1        1      141      0
301         301   57    1   0       130   131    0        1      115      1
302         302   57    0   1       130   236    0        0      174      0

     oldpeak  slope  ca  thal  target
0        2.3      0   0     1       1
1        3.5      0   0     2       1
2        1.4      2   0     2       1
3        0.8      2   0     2       1
4        0.6      2   0     2       1
..       ...    ...  ..   ...     ...
298      0.2      1   0     3       0

/tmp/ipython-input-1301851219.py:17: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  print(df.replace(to_replace=np.nan))